apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
spec:
  selector:
    env: dev  # Le label commun que vous souhaitez ajouter à tous les services
  ports:
    - protocol: TCP
      port: 80  # Port du service ClusterIP

