apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-pod  # Utilisez les mêmes libellés que ceux dans le template du pod
  template:
    metadata:
      labels:
        app: client-pod  # Utilisez les mêmes libellés que ceux dans le sélecteur du déploiement
    spec:
      containers:
        - name: client-container
          image: leonelmaken/client-service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-pod  # Utilisez les mêmes libellés que ceux dans le template du pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort


