apiVersion: v1
kind: Service
metadata:
  name: moderation-service
  labels:
    env: dev 
spec:
  selector:
    app: moderation-pod  # Utilisez le label du pod que vous souhaitez exposer
  ports:
    - protocol: TCP
      port: 80  # Port du service NodePort
      targetPort: 7000  # Port du conteneur dans le pod
  type: NodePort
