apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
spec:
  replicas: 3  # Vous pouvez ajuster le nombre de réplicas selon vos besoins
  selector:
    matchLabels:
      app: query-pod
  template:
    metadata:
      labels:
        app: query-pod
    spec:
      containers:
        - name: query-container
          image: leonelmaken/query-service:latest
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  type: ClusterIP
  selector:
    app: query-pod
  ports:
    - port: 4002
      targetPort: 4002

