apiVersion: v1
kind: Pod
metadata:
  name: query
  labels:
    app: query
    rel: stable
spec:
  containers:
    - name: query
      image: leonelmaken/query
      ports:
        - containerPort: 4002
      resources: {}
