apiVersion: v1
kind: Pod
metadata:
  name: query-pod
spec:
  containers:
  - name: query-container
    image: leonelmaken/query-service:latest  # Remplacez "version2" par le tag correct
    ports:
    - containerPort: 4002

