apiVersion: v1
kind: Pod
metadata:
  name: posts
  labels:
    app: posts
    rel: stable
spec:
  containers:
    - name: posts
      image: leonelmaken/posts
      ports:
        - containerPort: 4000
      resources: {}
