apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
spec:
  replicas: 3  # Vous pouvez ajuster le nombre de réplicas selon vos besoins
  selector:
    matchLabels:
      app: comments-pod
  template:
    metadata:
      labels:
        app: comments-pod
    spec:
      containers:
        - name: comments-container
          image: leonelmaken/comments-service:latest
          ports:
            - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  type: ClusterIP
  selector:
    app: comments-pod
  ports:
    - port: 4001
      targetPort: 4001

