apiVersion: v1
kind: Pod
metadata:
  name: comments-pod
  labels:
    app: comments
    rel: stable
spec:
  containers:
    - name: comments
      image: leonelmaken/comments
      ports:
        - containerPort: 4001
      resources: {}

