apiVersion: v1
kind: Service
metadata:
  name: query-service
  labels:
    env: dev
spec:
  selector:
    app: query-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

