apiVersion: v1
kind: Pod
metadata:
  name: moderation
  labels:
    app: moderation
    rel: stable
spec:
  containers:
    - name: moderation
      image: leonelmaken/moderation
      ports:
        - containerPort: 4003
      resources: {}
