apiVersion: v1
kind: Service
metadata:
  name: moderation-service-lb
spec:
  selector:
    app: moderation-pod  # Assurez-vous que le label du sélecteur correspond à celui de votre pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4003  # Port du conteneur dans le pod
  type: LoadBalancer

