apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
spec:
  replicas: 3  # Vous pouvez ajuster le nombre de réplicas selon vos besoins
  selector:
    matchLabels:
      app: moderation-pod
  template:
    metadata:
      labels:
        app: moderation-pod
    spec:
      containers:
        - name: moderation-container
          image: leonelmaken/moderation-service:latest
          ports:
            - containerPort: 4003
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service
spec:
  type: ClusterIP
  selector:
    app: moderation-pod
  ports:
    - port: 4003
      targetPort: 4003

