apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector:
    app: event  # Assurez-vous que le sélecteur correspond à celui de votre pod
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005

