apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-pod  # Assurez-vous que le sélecteur correspond à celui de votre pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

